server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

#消费着将要去访问的微服务名称
server-url:
  nacos-user-service: http://nacos-payment-provider

feign:
  sentinel:
    enabled: true

